name: SQL JDBC issue
about: Database is not connected
title: "[25.1.2024]"
labels: task
assignees: YeminthanRiki, Pie3215

description: |
  ### Expected behavior
  connected to the database

  ### Actual behavior
  connecting to the database with no response

  ### Specification version 
  MySQL connector J 8.0.25

  ### Operating system
  Window, MacOS
